
development:
  adapter: postgresql
  database: pullrequest
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: pullrequest_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: pullrequest
  pool: 5
  timeout: 5000

